remove_tmpdir(): Support recursion / sub-directories
The existing code assumed that tmpdir only contained regular files,
not an entire hierarchy of files with sub-directories or the like.

In case sub-directories exist, the current code fails as follows:

line 176, in test_all_apps
    remove_tmpdir(tmpdir)
  File "/usr/local/lib/python3.5/dist-packages/osmopython-0.2.0-py3.5.egg/EGG-INFO/scripts/osmotestconfig.py", line 142, in remove_tmpdir
    os.unlink(os.path.join(tmpdir, f))
IsADirectoryError: [Errno 21] Is a directory: 'writtenconfig/ericsson'

Change-Id: I896b99032d94ba0cdd340a8eed7c7b625661ad69