osmotestconfig: fix return value of write_config()
This patch fixes the following exception, if the received string does
not match. The calling function just expects an integer.

----
TypeError: '>' not supported between instances of 'tuple' and 'int'
----

Change-Id: I24adfd344937bab1ab641327e59a25bf76e18591