tests/test_py3: fix deprecated loop arg
The loop arg has been removed in python 3.10. The same event loop will
be used without passing the argument, so it can be removed.

Fix for:
  TypeError: gather() got an unexpected keyword argument 'loop'

Related: https://stackoverflow.com/a/60315290
Related: https://docs.python.org/3/library/asyncio-task.html#asyncio.gather
Change-Id: I776bc463246e7a1a9adbb7c06012353d65694507